#!/bin/bash
# tilde out-of-box-experience
# used to bootstrap automation for a new linux workstation
set -x
set -eo pipefail

if (( UID != "0" )); then
  echo "Please run as root user"
fi

# salt-bootstrap is currently broken on Fedora 32 and Ubuntu 20
# due to python3.8 dropping distro package

dnf install salt-minion

function salt() {
  salt-call \
    --local \
    --file-root="" \
    --pillar-root="" \
    --retcode-passthrough \
    --id "$(hostname -s)" \
    --output-diff \
    --log-level=debug \
    --state-output="mixed_id" \
    --state-verbose=True \
    "$@"
}